version: '3'

services:

  web:
    build: .
    image: superms2/web:latest
    volumes:
      - '.:/code'
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: "nonspot"
      POSTGRES_USER: "nonspot"
      POSTGRES_PASSWORD: "789789789D"
    expose:
      - '5432'